#!/usr/bin/env node
/* Prints the Tailwind v4 `@source` and `@import` lines a consumer app should
   add to its CSS to pick up this package's compiled output. Resolves the
   actual install path so it works under pnpm hoisting, yarn PnP, or npm
   nested layouts without the consumer guessing relative depths.

   Usage:
     node node_modules/payload-plugin-shadcn-ui/scripts/print-source.mjs
   Or in a project script:
     "shadcn:print-source": "node node_modules/payload-plugin-shadcn-ui/scripts/print-source.mjs"

   Pipe to a file consumed via `@import` from custom.css, e.g.:
     pnpm shadcn:print-source > src/styles/.shadcn-ui.css
   then in custom.css:
     @import './styles/.shadcn-ui.css'; */

import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const dist = resolve(here, '..', 'dist')

process.stdout.write(`/* Generated by payload-plugin-shadcn-ui/scripts/print-source.mjs */\n`)
process.stdout.write(`@source '${dist}';\n`)
process.stdout.write(`@import '${dist}/themes.css';\n`)
process.stdout.write(`@import '${dist}/styles.css';\n`)
